version: '3'

services:
  # Netwark web service
  netwark:
    build: .
    restart: on-failure
    # Uncomment this part if you are developping new features
    #command: pserve --reload development.ini
    ports:
      - 127.0.0.1:6543:6543
    # Uncomment this part if you are developping new features
    volumes:
      - .:/opt/netwark
    depends_on:
      - db
      - rabbit
    links:
      - db:psql.netwark
      - rabbit:rabbit.netwark

  # Netwark backend
  backend:
    build: .
    restart: on-failure
    command: python netwark/bin/celery_backend.py development.ini
    # Uncomment this part if you are developping new features
    volumes:
      - .:/opt/netwark
    depends_on:
      - db
      - rabbit
    links:
      - db:psql.netwark
      - rabbit:rabbit.netwark

  # PostgreSQL database
  db:
    image: postgres:11-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ReallyBadPwd
      POSTGRES_DB: netwark
    volumes:
      - ./docker/data/pgdata:/var/lib/postgresql/data

  # RabbitMQ broker
  rabbit:
    image: rabbitmq:3.7-management-alpine
    restart: on-failure
    ports:
      - 127.0.0.1:15672:15672
