version: '3'

services:
  # Netwark web service
  netwark:
    build: .
    restart: on-failure
    # Uncomment this part if you are developping new features
    # command: poetry run pserve --reload production.ini
    ports:
      - 127.0.0.1:6543:6543
    #volumes:
    #   - ./development.ini:/opt/netwark/production.ini
    #   - ./:/opt/netwark # Uncomment this line if you are developping new features
    depends_on:
      - db
      - rabbit
    links:
      - db:psql.netwark
      - rabbit:rabbit.netwark

  # Netwark backend
  backend:
    build: .
    restart: on-failure
    command: poetry run python netwark/bin/celery_backend.py development.ini
    #volumes:
    #   - ./development.ini:/opt/netwark/production.ini
    #   - ./maxmind_db:/opt/netwark/maxmind_db:ro
    #   - ./:/opt/netwark  # Uncomment this line if you are developping new features
    depends_on:
      - db
      - rabbit
    links:
      - db:psql.netwark
      - rabbit:rabbit.netwark

  # PostgreSQL database
  db:
    image: postgres:11-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ReallyBadPwd
      POSTGRES_DB: netwark
    volumes:
      - ./docker/data/pgdata:/var/lib/postgresql/data

  # RabbitMQ broker
  rabbit:
    image: rabbitmq:3.7-management-alpine
    restart: on-failure
    ports:
      - 127.0.0.1:15672:15672
